/* Enemy and ally profiles from Chapter 8 of the corebook (Allies and Enemies).
   Skills are in the order: Agility, Athletics, Wits, Presence, Intuition, Knowledge, Resolve, Melee, Ranged, Lore (0 = can't).
   Abilities, weaknesses and gear are short summaries in our own words, not the book's text.
   The book prints each profile's dice pool in its art; "pool" here is only a starting suggestion, so check the book and adjust. */
window.APL_NPCS = (function(){
const MINOR = ['Minor NPC','Killed or knocked out (GM’s choice) as soon as it’s wounded.'];
const MAJOR = ['Major NPC','Can strain once to restore its pool limit to max. Wounded after that: killed or knocked out.'];
const MONSTROUS = ['Monstrous NPC','Huge and slow: every simple or complex action costs at least 2 dice, and it can’t react to avoid attacks.'];
const FLYER = ['Flyer','A move action can fly up to 20 ft.'];
const STEALTHY = ['Stealthy','Spotting or finding it is difficult. In a surprise round it refills its whole pool.'];
const COUNTER = ['Counterspell','Spell. When someone within 50 ft casts a spell, a Lore reaction (−1 to the die) makes it fail. A 1 costs it 1 horror.'];
const FERVOR = ['Fanatical Fervor','Advantage on Melee Combat and Resolve actions while within 30 ft of another cult member. Horror dice limit starts at 3.'];
const EATLEAD = ['Eat Lead!','Before a ranged attack with 2+ ammo circles, may spend one ammo to add a die.'];
const SWARM = ['Swarm','Can’t be injured; each hit deals only 1 damage unless it’s fire, explosives or something the GM rules works well on swarms. Crawls through small gaps and on walls. Heals 1 damage at the start of its turn.'];
const NIGHT = ['Creatures of the Night','Disadvantage on everything in sunlight.'];
const HUNGER = ['Hunger','Can’t react to avoid attacks while it can see a corpse.'];
const FRENZY = ['Corpse Frenzy','While it can see a corpse, may reroll one die on complex Agility, Athletics or Melee Combat actions.'];
const DEEP = ['Creatures of the Deep','Won’t willingly come within 5 ft of open flame. If burned or damaged by fire, it flees the scene.'];
const FORMLESS = ['Formless Form','Reduces all damage by 3 (to a minimum of 0). Heals 1 damage at the start of its turn.'];
const AMORPH = ['Amorphous','Never slowed by terrain or doors. Can’t be injured.'];
const TOUGH = 'Tough hide: −1 damage from attacks (minimum 1).';
return [
// ---------- Generic NPCs ----------
{n:'Arcane Initiate',cat:'Generic NPCs',type:'Minor',pool:4,sk:[5,5,5,6,5,4,4,6,6,4],
 ab:[MINOR,['Amateur Sorcerer','A 1 on a complex Lore action costs it 1 horror; two or more 1s give it and everyone within 30 ft 1 horror.'],
  ['Arc of Lightning','Spell. Complex Lore action on a target within 100 ft: 1 damage +1 per success. Each 6 hits another target within 100 ft for the same. Any 1s: it takes 2 damage.'],COUNTER],
 atk:[],gear:'Mantle of Protection: −1 damage from every source (minimum 1). Maybe one tome.'},
{n:'Cultist',cat:'Generic NPCs',type:'Minor',pool:4,horror:3,sk:[5,5,5,6,5,6,4,4,5,5],
 ab:[MINOR,FERVOR],atk:[['Ritual Knife','Melee',2,3,'Engaged',''],['.32 ACP Pistol','Ranged',2,4,'30 ft','Ammo 2']],
 gear:'Cult robes: may reroll a reaction to avoid a ranged attack once.'},
{n:'Cult Leader',cat:'Generic NPCs',type:'Major',pool:5,horror:3,sk:[5,5,5,4,5,4,3,5,5,3],
 ab:[MAJOR,FERVOR,['Sacrificial Ally','When hit, a Resolve reaction redirects the hit to an engaged NPC ally.'],
  ['Steal Life','Spell. Complex Lore action on someone within 50 ft: unless they pass a Resolve reaction, they take 2 damage and 1 horror and it heals 3.']],
 atk:[['Enchanted Dagger','Melee',2,2,'Engaged','']],gear:'Cult robes: may reroll an Agility reaction against a ranged attack once. $100.'},
{n:'Drifter',cat:'Generic NPCs',type:'Minor',pool:4,sk:[5,5,4,4,4,6,5,5,6,6],
 ab:[MINOR,['Tales of the Road','Once per session, complex Presence action: allies within 20 ft lower their horror dice limit by 2 and get advantage on Resolve actions for the scene. Two or more 1s: one ally within 20 ft (GM picks) suffers a trauma.'],
  ['Skedaddle','May reroll reactions to avoid melee or ranged attacks.']],
 atk:[['Pocketknife','Melee',1,4,'Engaged','Very hard to find']],gear:'Heavy clothing: −1 melee damage (minimum 1).'},
{n:'Gangster',cat:'Generic NPCs',type:'Minor',pool:4,sk:[5,4,5,6,5,6,5,5,4,6],
 ab:[MINOR,EATLEAD,['Sucker Punch','When someone tries to disengage from it, an Athletics reaction knocks them prone and stops their movement for the turn; on a 6 they also take 1 damage.']],
 atk:[['Colt Police Revolver','Ranged',2,4,'75 ft','Ammo 2, slow reload'],['Pearl-Handled Switchblade','Melee',2,4,'Engaged','Hard to find']],gear:'$50, a car (the boss’s).'},
{n:'Healer',cat:'Generic NPCs',type:'Minor',pool:4,sk:[5,6,5,4,5,3,5,6,6,6],
 ab:[MINOR,['Healer','Mundane healing with 3+ successes also heals one injury.'],['Psychiatric Counselor','When it lowers someone’s horror dice limit, it lowers it by 2 instead of 1.']],
 atk:[],gear:'Medical supply bag: +1 success on successful healing actions.'},
{n:'Law Enforcement',cat:'Generic NPCs',type:'Minor',pool:4,sk:[5,5,5,5,4,6,6,4,4,6],
 ab:[MINOR,['Bell Ringer','Once per scene with a baton, a complex Melee Combat action gives an engaged target the Heavy Blow injury; they can’t stand while engaged with it.']],
 atk:[['Colt Police Revolver','Ranged',2,4,'75 ft','Ammo 2, slow reload'],['Police Baton','Melee',2,4,'Engaged','2+ successes: target knocked prone']],gear:'Badge, flashlight, handcuffs.'},
{n:'Mafia Leader',cat:'Generic NPCs',type:'Major',pool:5,sk:[5,5,4,4,4,5,3,5,3,6],
 ab:[MAJOR,EATLEAD,['Vicious Leadership','Complex Resolve action: all its allies ignore traumas (current and new) until the end of its turn.']],
 atk:[['Gold-Plated Colt 1911','Ranged',2,3,'75 ft','Ammo 2'],['Pearl-Handled Tommy Gun','Ranged',2,3,'75 ft','Ammo 5, +1 damage per success']],
 gear:'Silk bulletproof vest: −1 ranged damage (minimum 1). $250, an entourage of mobsters.'},
{n:'Professor',cat:'Generic NPCs',type:'Minor',pool:4,sk:[6,6,5,5,5,3,4,6,6,4],
 ab:[MINOR,['Font of Knowledge','Simple action: another character adds 1 die to their next Knowledge or Lore complex action this scene.']],atk:[],gear:'May own (and read) one tome.'},
{n:'Reporter',cat:'Generic NPCs',type:'Minor',pool:4,sk:[5,6,5,5,4,5,5,6,6,5],
 ab:[MINOR,['Skilled Questioner','In a narrative scene, complex Intuition action: its questioning gets advantage and others react to its questions with disadvantage.']],
 atk:[],gear:'Trench coat: may reroll a reaction to avoid an attack once. Press camera and pass.'},
{n:'Townsperson',cat:'Generic NPCs',type:'Minor',pool:3,sk:[6,5,5,5,5,5,5,6,6,6],
 ab:[MINOR,['Infinite Diversity','+1 to each die on complex actions tied to its profession.']],atk:[['Unarmed','Melee',1,0,'Engaged','']],gear:'Tools of its trade.'},
{n:'Vermin Swarm',cat:'Generic NPCs',type:'Minor',pool:3,sk:[3,5,0,0,5,0,6,4,0,0],
 ab:[MINOR,['Creeping Poison','Any injury it inflicts is the Sickened injury.'],SWARM],
 atk:[['Bite/Sting','Melee',1,3,'Engaged','Mundane armor doesn’t reduce it']],gear:''},
{n:'Wild or Guard Dog',cat:'Generic NPCs',type:'Minor',pool:3,sk:[5,4,5,6,5,0,4,4,0,0],
 ab:[MINOR,['Fast','Once per turn, if not engaged, moves up to 20 ft as a free action.'],['Pack Tactics','+1 die when attacking someone engaged with one of its allies.']],
 atk:[['Bite/Claw','Melee',2,3,'Engaged','2+ successes on a human-sized target: knocked prone']],gear:''},
// ---------- Named characters ----------
{n:'Agatha Crane',cat:'Named characters',type:'Named',pool:5,sk:[6,5,4,5,4,3,3,6,6,4],
 ab:[['Empirical Data','Once per session in a narrative scene, when an investigator fails a Knowledge action, they can go over the evidence with her: gain 1 insight and retry with +1 to each die.'],
  ['Parapsychologist','In a narrative scene, complex Knowledge action: one engaged ally lowers their horror dice limit by 3.']],atk:[],gear:'Keys to the Miskatonic science building.'},
{n:'Carl Sanford',cat:'Named characters',type:'Named',pool:5,sk:[5,5,3,4,3,3,4,4,5,3],
 ab:[['Always Prepared','Once per scene, a simple action produces any non-unique relic or tome from Chapter 4 (and he can read it).'],COUNTER,
  ['Silver-Tongued','Lies with 2+ successes can’t be seen through; with 3+ he adds a free second lie.']],
 atk:[['Enchanted Dagger','Melee',2,2,'Engaged','']],gear:'Talisman of Protection (3 uses per session): when hit, take 0 damage and no injury. $300, Silver Twilight Lodge ring.'},
{n:'Doctor Henry Armitage',cat:'Named characters',type:'Named',pool:5,sk:[5,6,4,4,5,3,4,6,5,3],
 ab:[['Occultologist','Once per session in a narrative scene, when an investigator fails a Lore action, they can go over the evidence with him: gain 1 insight and retry with +1 to each die.'],
  ['Wealth of Knowledge','When he aids an investigator’s Knowledge or Lore action, they may use his skill rating instead of theirs.']],atk:[],gear:'Keys to the Orne Library.'},
{n:'Calvin Wright',cat:'Named characters',type:'Named',pool:5,sk:[5,4,3,6,4,6,3,4,5,6],
 ab:[['Been Through Hell','Once per turn, when he or an ally within 30 ft suffers a trauma, reduce the trauma roll by 2 (minimum 1).'],
  ['Not Done Yet','Once per session, complex Resolve action: pool limit back to max; with 2+ successes he also heals an injury.'],
  ['Protector','When an engaged ally would be hit, a Resolve reaction takes the hit instead; on a 6 both avoid it.']],
 atk:[['Colt 1911 Pistol','Ranged',2,3,'75 ft','Ammo 2'],['Bowie Knife','Melee',2,3,'Engaged','+2 to injury rolls']],gear:''},
{n:'Father Mateo Castile',cat:'Named characters',type:'Named',pool:5,sk:[5,6,4,3,4,4,3,6,6,3],
 ab:[['Inspirational Healing','Faith. Complex Lore action on himself or someone within 10 ft: heal up to 3 damage; with 3+ successes they also add dice equal to the damage healed.'],
  ['Exile the Supernatural','Faith. Once per scene, complex Resolve action on an engaged, possessed character: they get a Resolve reaction to throw it off, +1 per extra success.'],
  ['Light in the Darkest Hour','Faith. Once per session before the investigators’ turn: until the next turn he and all allies ignore injuries and traumas and can’t get new ones.']],
 atk:[],gear:'Religious symbol: once per session, a simple action adds a success to a successful Lore or Presence action.'},
// ---------- Supernatural creatures ----------
{n:'Children of Yig',cat:'Supernatural creatures',type:'Minor',pool:4,sk:[3,5,5,6,5,4,4,3,5,3],
 ab:[MINOR,['Alter Appearance','After an hour-long ritual sacrifice, can take on the victim’s exact appearance (losing its bite and claws while disguised).'],
  ['Venomous Bite','Once per encounter, a Melee Combat action gives an engaged target the Sickened injury unless they react to avoid it. Each new scene they must pass an Athletics action or be Sickened again, until cured (witch hazel poultice cures it).']],
 wk:[['Snakelike','Disadvantage in extreme cold, or within 10 ft of wormwood, ammonia, sulfur or vinegar.']],
 atk:[['Fangs and Claws','Melee',2,3,'Engaged',''],['Blowgun','Ranged',1,3,'20 ft','Always inflicts Sickened; hard to find']],gear:TOUGH},
{n:'Comets',cat:'Supernatural creatures',type:'Minor',pool:4,sk:[4,3,5,6,6,5,5,5,5,4],
 ab:[MINOR,['Child of Asterias','Heals 2 damage at the start of its turn, and one injury at the start of each scene.'],['Clone','+1 to each die on actions tied to the profession of the person it copies.']],
 wk:[['Unregulated Acidity','Doused in or fed vinegar: permanently loses Child of Asterias.'],['Saltwater Organism','Disadvantage on everything if it hasn’t soaked in saltwater in the last day.']],
 atk:[['Powerful Strike','Athletics',3,4,'Engaged','3+ successes: thrown back 5 ft and prone']],gear:''},
{n:'Deep One',cat:'Supernatural creatures',type:'Minor',pool:4,sk:[4,3,5,6,4,6,3,4,5,5],
 ab:[MINOR,['Grotesque Horde','Anyone starting their turn within 10 ft of three or more Deep Ones suffers 1 horror and has disadvantage on reactions to avoid attacks until their next turn.'],['Sea Creature','Breathes underwater; a simple action swims 10 ft.']],
 wk:[DEEP],atk:[['Teeth and Claws','Athletics',2,4,'Engaged',''],['Harpoon','Melee',3,3,'10 ft',''],['Harpoon (thrown)','Ranged',3,3,'30 ft','Single use']],gear:'Two harpoons.'},
{n:'Formless Spawn',cat:'Supernatural creatures',type:'Minor',pool:4,sk:[5,5,6,6,6,6,6,5,6,4],
 ab:[MINOR,AMORPH,FORMLESS,['Smother','A tendril hit with 3+ successes can engulf the target instead of injuring: they can’t move, disengage with disadvantage, and take 2 damage and 2 horror each turn until they escape.'],STEALTHY],
 wk:[['Magical Vulnerability','Formless Form doesn’t reduce damage from spells or enchanted weapons.'],['Acidic','Doused or injected with an alkali (baking soda, lye): loses Formless Form for the scene.']],
 atk:[['Tendril Slam','Melee',3,3,'10 ft','']],gear:''},
{n:'Ghoul',cat:'Supernatural creatures',type:'Minor',pool:4,sk:[4,4,6,6,6,6,5,4,6,6],
 ab:[MINOR,FRENZY,['Consume','Once per scene, a simple action to feed on an engaged corpse: +2 pool limit (up to max). Witnesses within 20 ft suffer 1 horror unless they pass a Resolve reaction.']],
 wk:[NIGHT,HUNGER],atk:[['Teeth and Claws','Melee',2,3,'Engaged','']],gear:TOUGH},
{n:'Ghoul Priest',cat:'Supernatural creatures',type:'Major',pool:5,sk:[5,5,5,4,5,4,4,4,6,4],
 ab:[MAJOR,FRENZY,['Ghoul Shepherd','Complex Presence action: all allied ghouls within 30 ft move up to 15 ft as a free action.'],
  ['The Hunger','Faith. Once per scene, complex Lore action: per success, one character within 100 ft takes 1 damage and 1 horror and it heals 1.'],
  ['Blood of Umôrdhoth','A human forced to drink it must pass a difficult Resolve action or turn into a ghoul over five minutes (or five rounds). Counterspell can stop it in time.']],
 wk:[NIGHT,HUNGER],atk:[['Teeth and Claws','Melee',2,3,'Engaged','']],gear:TOUGH},
{n:'Hound of Tindalos',cat:'Supernatural creatures',type:'Major',pool:5,sk:[2,5,6,6,4,5,5,3,0,6],
 ab:[MAJOR,['Vaporous Entrance','Once per round, a simple action to vanish into or appear from any corner or angle; next turn it can reappear at any other angle.'],
  ['Quick Dodge','After successfully reacting to a ranged attack, may move up to 10 ft.'],STEALTHY],
 wk:[['The Curves of Time and Space','Can’t cross an unbroken circle drawn or laid on the floor or ground.']],
 atk:[['Teeth and Claws','Melee',3,3,'Engaged','2+ successes: target knocked prone'],['Tongue Lash','Melee',1,2,'10 ft','Only vs prone or helpless targets; +3 to injury rolls']],gear:''},
{n:'Nightgaunt',cat:'Supernatural creatures',type:'Minor',pool:4,sk:[3,4,6,6,5,6,5,4,0,0],
 ab:[MINOR,['Grappler','Complex Athletics action: an engaged target is grappled unless they pass an Agility or Athletics reaction. Grappled targets can’t move until they disengage, and it can carry them when it moves.'],FLYER,STEALTHY],
 wk:[NIGHT],atk:[['Trident','Melee',3,3,'Engaged','3+ successes: target drops a weapon'],['Barbed Tail','Melee',1,4,'10 ft','3+ successes: target knocked prone']],gear:''},
{n:'Poltergeist',cat:'Supernatural creatures',type:'Minor',pool:4,sk:[3,5,5,5,5,5,5,5,5,5],
 ab:[MINOR,['Ethereal','Passes through solid objects and terrain. Attacks against it have disadvantage, it can’t be injured and attack damage is reduced to 0.'],
  ['The Haunting','Once per scene, a simple action does something terrifying: at the start of their next turn, everyone else suffers 1d3 horror unless they pass a Resolve action.']],
 wk:[['Restless Dead','Finishing its unfinished task (justice, a last wish) makes it vanish for good.'],['Spirit Creature','Enchanted weapons and faith or spell knacks damage it normally.']],
 atk:[['Thrown Items','Ranged',1,4,'20 ft','']],gear:''},
{n:'Zombie',cat:'Supernatural creatures',type:'Minor',pool:4,sk:[6,4,6,0,6,0,2,5,0,0],
 ab:[MINOR,['Ghastly Encounter','The first time a character meets zombies in a session: 1 horror (2 if one was someone they knew) unless they pass a Resolve action.'],['Undead','Reduces all damage to 0, but can still be injured.']],
 wk:[['Headshot','An attack that rolls any 6s damages it normally.']],
 atk:[['Rotting Teeth','Melee',2,0,'Engaged','Anyone damaged must pass an Athletics action next turn or be Sickened']],gear:''},
// ---------- Eldritch monstrosities ----------
{n:'Byakhee',cat:'Eldritch monstrosities',type:'Major',pool:6,sk:[3,3,5,5,4,5,4,2,6,5],
 ab:[MAJOR,FLYER,['Screeching Terror','Once per scene, complex Presence action: everyone else must pass a Resolve action at the start of their turn or suffer 2 horror and disadvantage on everything until their next turn.']],
 wk:[['Summoned Being','Banishing spells and knacks against it get +1 to each die.']],
 atk:[['Rending Claws','Melee',4,4,'Engaged','+2 to injury rolls']],gear:''},
{n:'Elder Thing',cat:'Eldritch monstrosities',type:'Major',pool:6,sk:[4,2,3,6,5,2,2,2,6,3],
 ab:[MAJOR,['Countermagic','When someone within 100 ft casts a spell, a Lore reaction makes it fail.'],FLYER,
  ['Masters of Science','Complex Knowledge action, pick one: give someone within 50 ft the Sickened injury; turn the air within 50 ft to nitrogen until its next turn (suffocation for others); learn and switch devices within 10 ft on or off; or send an otherworldly NPC within 20 ft home unless it passes a Resolve reaction.'],
  ['Terrifying','First sight of it: pass a Resolve action next turn or suffer 2 horror and a trauma.']],
 atk:[['Tentacle Strike','Melee',2,3,'10 ft','+1 damage per extra success; 3+ successes: thrown back 5 ft and prone']],gear:'Very tough hide: −2 damage from attacks (minimum 1).'},
{n:'Hune-Mist',cat:'Eldritch monstrosities',type:'Minor',pool:4,sk:[3,4,6,6,4,5,4,4,0,6],
 ab:[MINOR,FLYER,['Mist and Shadow','Passes through solid objects and terrain. Attacks against it have disadvantage and it can only suffer the Burned injury.'],
  ['Enervate','Anyone starting their turn engaged with it takes 1d3 damage and 1 horror unless they pass an Athletics action.']],
 wk:[['Being of Cold and Mist','Starting its turn engaged with fire or strong heat gives it the Burned injury.']],
 atk:[['Ethereal Talons','Melee',2,3,'Engaged','Only magic can reduce or prevent its damage and injuries']],gear:''},
{n:'Hunting Deep One',cat:'Eldritch monstrosities',type:'Major',size:'Large',pool:6,sk:[4,3,5,6,4,6,4,3,6,5],
 ab:[MAJOR,['Deep One Curse','Once per session, very difficult Lore action: curse a character (they gain Creatures of the Deep and attack Deep Ones with disadvantage). Once a day they may try a very difficult Resolve or Lore action to lift it; after 1d3+3 days they become a Deep One.'],
  ['Frightening','First sight of it: pass a Resolve action next turn or suffer 2 horror.'],
  ['Hull Buster','Complex Athletics action: an engaged vehicle is heavily damaged (destroyed with 3+ successes), or a 10×10 ft section of dock or wall is smashed.']],
 wk:[DEEP],atk:[['Bite/Claw','Melee',3,4,'5 ft (10 ft max)','']],gear:'Large: takes up a 10×10 ft space.'},
{n:'Shoggoth',cat:'Eldritch monstrosities',type:'Monstrous',size:'Huge',pool:7,sk:[5,2,5,6,5,5,4,3,6,4],
 ab:[MAJOR,MONSTROUS,AMORPH,['Crushing Assault','Complex Melee Combat action: per success, one engaged character must pass an Agility reaction or take 5 damage and fall prone.'],FORMLESS,
  ['Terrifying','First sight of it: pass a Resolve action next turn or suffer 2 horror and a trauma.']],
 wk:[['Ancient Hatred','Seeing a sign of the Elder Things gives it disadvantage on everything and it tries to destroy the sign and whoever carries it.'],['Protoplasmic Body','Fire and explosives ignore Formless Form.']],
 atk:[['Tendril Strike','Melee',4,3,'20 ft','']],gear:'Huge: takes up a 15×15 ft space.'},
{n:'Star Spawn',cat:'Eldritch monstrosities',type:'Monstrous',size:'Titanic',pool:8,sk:[4,2,3,5,4,3,3,3,5,2],
 ab:[MAJOR,MONSTROUS,['Pick Up And…','Very difficult Athletics action: grapple an engaged character (disengaging from it has disadvantage). At the start of its turn it may throw them up to 50 ft (a fall of that distance) or swallow them whole (they die).'],
  ['Supremely Terrifying','First sight of it: pass a difficult Resolve action next turn or suffer 4 horror and a trauma.']],
 atk:[['Titanic Talons','Melee',6,3,'10 ft','3 successes: everyone else within 10 ft of the target also takes 6 damage']],
 gear:'Very thick hide: −3 damage from attacks (minimum 0), and only 4+ damage after that can injure it. Titanic: takes up a 30×30 ft space.'},
{n:'Trylogog Swarm',cat:'Eldritch monstrosities',type:'Major',size:'Titanic',pool:6,sk:[3,3,0,0,6,0,4,4,0,0],
 ab:[MAJOR,['Enveloping Horror','Can share space with others; anyone starting their turn inside it takes 1 damage (mundane armor doesn’t help) and 1 horror.'],
  ['Flesh Reaping','Heals 1 damage whenever it inflicts an injury.'],FLYER,SWARM],
 wk:[['Sonic Sensitivity','A very loud noise within 20 ft (bell, gong, foghorn) scatters it: it discards up to half its dice and must pass a Resolve action before doing anything else.']],
 atk:[['Many Chewing Mandibles','Melee',1,3,'Engaged','+1 damage per success; mundane armor doesn’t reduce it']],gear:'Titanic: takes up a 30×30 ft space.'},
];
})();
/* The book's NPC trauma table (Table 8–1): roll 1d6, +1 per 1 on a horror die. */
window.APL_NPC_TRAUMAS = [
 ['1–3','Cower','This turn and next, it must save at least half its dice and use them only for reactions.'],
 ['4–5','Flee','This turn and next, it must spend at least half its dice moving away from all opponents, and can’t move closer to any.'],
 ['6','Panicked','For the scene, disadvantage on everything; other NPCs engaged with it also have disadvantage.'],
 ['7+','Stupefied','For the scene, refilling its pool only adds one die.']
];
